CREATE DATABASE events;
CREATE DATABASE users;
CREATE DATABASE requests;
CREATE DATABASE comments;

GRANT ALL PRIVILEGES ON DATABASE events TO username;
GRANT ALL PRIVILEGES ON DATABASE users TO username;
GRANT ALL PRIVILEGES ON DATABASE requests TO username;
GRANT ALL PRIVILEGES ON DATABASE comments TO username;