CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    last_action_time TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_event UNIQUE (user_id, event_id)
);

CREATE TABLE event_similarities (
    id BIGINT PRIMARY KEY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_event_pair UNIQUE (event_a, event_b),
    CONSTRAINT check_event_order CHECK (event_a < event_b)
);